### ISSUE TITLE
data stuck on diffrent song 

### ISSUE THREAD

**Issue by zivoy** [Mystogan98/BeatSaviorData#2]
I am not sure how to reproduce the bug.
I was playing, then I played The Devil and failed
I think I restarted.
then when I went to play other songs it stopped showing new data.

![20201119204246_1](https://user-images.githubusercontent.com/16857861/99747361-5e4e6380-2aa8-11eb-9cb4-855597fc16ff.jpg)
![20201119204258_1](https://user-images.githubusercontent.com/16857861/99747364-60182700-2aa8-11eb-8cc6-fe5bca6ff5ce.jpg)

edit: this is on version 2.0.1.2 that released 3 hours ago

**Comment by zivoy** [comment]
I belive this happens after a match when you play solo again

**Comment by Mystogan98** [comment]
Could you please send me your file named "latest.log", which in your "Logs" folder, inside o your Beat Saber folder please ? You can send it here or via Discord (Mystogan#5963).
That will give me any error message that happened during your last session, so I can start debugging from that. If the bug did not happen during your last session, logs are kept in .zip file with the date and time as name.

Thanks for the report !

**Comment by zivoy** [comment]
[_latest.log](https://github.com/Mystogan98/BeatSaviorData/files/5594229/_latest.log)
if it helps in this log it should be stuck on the song Virus
