### ISSUE TITLE
Speed seems exaggerated

### ISSUE THREAD

**Issue by mgreen442** [Mystogan98/BeatSaviorData#3]
Where on the saber is the speed calculated? It just says right or left hand, but it also says my right hand moved 200kph on one song. That can't be right, can it?

**Comment by redegg89** [comment]
I wouldn't be surprised if it was, but sadly, I can't test if it is because I have no way to measure the speed of my hand.

**Comment by Mystogan98** [comment]
The speed is computed around the tip of the saber, ~1 meter away from your hand. It is very likely to be right, especially as it is directly given by the game. Also know that it only computes the speed when you cut blocks, so only your swings matters
