### ISSUE TITLE
Oculus Quest 1 Installation

### ISSUE THREAD

**Issue by jaysee260** [Mystogan98/BeatSaviorData#4]
Hey, looking for some help here. Can someone provide instructions on how to install this on the Quest 1? I've downloaded the DLL but am not sure where in the device's file system to place it.

Please let me know if there's any info I need to provide.

**Comment by Mystogan98** [comment]
Hey,

Sadly the mod isn't available for Quests. Because it is a completly different architecture, it would require me to learn a new language and recreate more or less the entire mod, as well as recreate missing dependencies.

**Comment by jaysee260** [comment]
Gotcha @Mystogan98, thanks anyways! Out of curiosity, which device(s) is it available on?

**Comment by Mystogan98** [comment]
Well, there is only 2 versions of the game, th PC version (Windows architecture) and the Quest version (Android architecture). Doesn't matter what headset, as long as you run the game from a computer.

(Yes there is also PSVR, but there's no mod at all on it)
