### ISSUE TITLE
Data does not save locally when there is a problem uploading to the server

### ISSUE THREAD

**Issue by motzel** [Mystogan98/BeatSaviorData#7]
It didn't send me yesterday's results to the server because it seems to be overloaded lately. But I was hoping that the locally saved files in %AppData%/Roaming/Beat Savior Data contained the correct data. Unfortunately, it seems that when there is uploading error, they are not saved locally as well. There is only one line with total stats in the file from yesterday.

**Comment by Mystogan98** [comment]
Hello,

All uploading issue should be fixed by now (we moved to a bigger database), and issues with the FileManager should be fixed in the latest version too.
