### ISSUE TITLE
Add CORS headers to API endpoint

### ISSUE THREAD

**Issue by motzel** [Mystogan98/BeatSaviorData#8]
I tried to access an API endpoint (https://www.beatsavior.io/api/livescores/player/) from the browser, but the request was denied. Server response does not contains required CORS headers.

Could you consider adding 
```
access-control-allow-origin: *
```
header to the server response?

**Comment by Mystogan98** [comment]
Hello,

I am not the one making the website and API, but I'll transfer your request to Neurosis. The best place for this kind of suggestion is on our discord, where we are both present : https://discord.gg/tNBWdeA
